/*
-- Query: SELECT * FROM dbms_project.amenities
LIMIT 0, 1000

-- Date: 2022-04-26 16:40
*/
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (1,1,'N','Y',1,'Y','Y','N','Y','N','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (2,2,'Y','Y',1,'Y','Y','Y','Y','Y','N','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (3,3,'Y','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (4,4,'N','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (5,5,'N','Y',1,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (6,6,'N','Y',1,'Y','Y','N','Y','N','N','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (7,7,'N','Y',1,'Y','Y','N','Y','N','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (8,8,'Y','Y',1,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (9,9,'N','Y',1,'Y','Y','Y','Y','N','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (10,10,'Y','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (11,11,'N','Y',1,'Y','Y','N','Y','N','N','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (12,12,'N','Y',1,'Y','Y','N','Y','N','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (13,13,'Y','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (14,14,'N','Y',1,'Y','Y','N','Y','N','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (15,15,'Y','Y',1,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (16,16,'N','Y',1,'Y','Y','N','Y','N','N','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (17,17,'N','Y',1,'Y','Y','N','Y','N','N','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (18,18,'Y','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (19,19,'N','Y',1,'Y','Y','N','Y','N','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (20,20,'Y','Y',2,'Y','Y','Y','Y','Y','N','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (21,21,'Y','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (22,22,'N','Y',1,'Y','Y','N','Y','N','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (23,23,'Y','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (24,24,'N','Y',1,'Y','Y','N','Y','N','N','Y','Y');
INSERT INTO `` (`Furnishing_Id`,`Property_Id`,`Is_Air_Condition`,`Is_Parking`,`Number_Of_Parking`,`Is_Central_Heating`,`Is_Laundry`,`Is_Fireplace`,`Are_Closets`,`Is_Backyard`,`Are_Pets_Allowed`,`Is_Microwave`,`Is_Dishwasher`) VALUES (25,25,'Y','Y',2,'Y','Y','Y','Y','Y','Y','Y','Y');
